# https://taskfile.dev

version: '3'

silent: true



tasks:
  default:
    cmds:
    - task: syntax
    - task: palette
    # - task: theme

  syntax:
    sources:
    - ./syntaxes/rust.yaml
    method: timestamp
    cmds:
    - ./scripts/to_json ./syntaxes/rust.yaml ./syntaxes/rust.json

  palette:
    sources:
    - src/languages/*.yaml
    - src/*.yaml
    cmds:
    - ./scripts/compiler --quick
    - sha1sum acid.json

  # watch-theme:
  #   sources:
  #   - ./acid.json
  #   - ./syntaxes/rust-extras.tmLanguage.json
  #   method: timestamp
  #   cmds:
  #   - make package-theme

